name: Rust Linux

on:
  push:
    branches: ["mdw-gamestate"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Compile nightly build
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

      - name: Upload nightly build
        uses: actions/upload-artifact@v4
        with:
          name: logger_nightly
          path: target/debug/logjam
